### ISSUE TITLE
Componente RedesSociais

### ISSUE THREAD

**Issue by tarsojabbes** [Guardians-DSC/guardians#6]
### O que deve ser implementado?

Precisamos que o componente de RedesSociais seja implementado seguindo nossa [prototipação](https://www.figma.com/file/k9SOlpMebhcIvJ8089QmfZ/GuardiansUFCG?node-id=1%3A3).

![image](https://user-images.githubusercontent.com/60106453/195444825-918ed703-a55f-4a93-a5a7-6b4a606281e2.png)

### Como deve ser implementado?

O componente recebe três props: instagramUrl, linkedinUrl e githubUrl. Todas são obrigatórias e redirecionam o usuário para a rede social respectiva.

### Contexto adicional

- As cores utilizadas estão no arquivo global de CSS
- Crie sua branch a partir da branch <code>development</code>
- Nossa estrutura de pastas é: NomeDoComponente e dentro da pasta dois arquivos, o index.jsx e o styles.js (Utilizamos Styled-Components)

**Comment by MariaEduardaDeAzevedo** [comment]
Opa! Tenho interesse em contribuir construindo esse componente! Posso pegar essa issue?

**Comment by tarsojabbes** [comment]
Com certeza! Vou te dar o assign :)

**Comment by MariaEduardaDeAzevedo** [comment]
Valeu!
